# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.11.4"
  revision = "8c97d6ab64da020f8b151e9d3ed8af3172f5c390"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.11.4"
  revision = "37c5ce6f2f592fbbd798bb86a8814d0918b3abe1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.11.4"
  revision = "67bb9d92aa024a38a3e323cbb9e115e82c0d50b3"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.11.4"
  revision = "8ee1a638bafa4ae9691077e690cb45dd54f45111"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.11.4"
  revision = "3db8bfc8858dc9a5d6e7ef5817f58a7ca30b0c6a"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.3.10"

[[override]]
  name = "google.golang.org/grpc"
  version = "=1.14.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.13.8"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "=1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "=0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.0.4"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "=11.3.0-beta"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
