apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-backup-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      containers:
      - name: etcd-backup-operator
        image: quay.io/coreos/etcd-operator:v0.9.4
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
